# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Default
  demands: 
    Unity_2021.3.24f1
steps:
- task: UnityBuildTask@3
  inputs:
    buildTarget: 'standalone'
    unityEditorsPathMode: 'specify'
    customUnityEditorsPath: 'C:\Program Files\Unity\Hub\Editor'
    versionSelectionMode: 'project'
    outputPath: '$(Build.BinariesDirectory)'
    outputFileName: 'test-project-output'
#hi